### ISSUE TITLE
WordPress headless with vue.js

### ISSUE THREAD

**Issue by gregoirepuget** [snipcart/wordpress-headless-vue#2]
Hello,

Just a thank you,

We created our Wordpress headless with vue.js, taking advantage of what you have done on this repo.
Here is the site : [36 Pixels](https://www.36pixels.fr)

The site is very fast and scores higher than 90 on Google PageSpeed ​​Insights

Grégoire

**Comment by JeanSebTr** [comment]
Bonjour @gregoirepuget !

Merci pour le partage, bien heureux que notre contenu est pu vous être utile!
